# Model and dataset for experiment
model: "baseline_cnn"
dataset: "mitbih"

seed: 1234

# Training parameters
device: "cpu"
batch_size: 32
n_epochs: 20
early_stopping: true
train_val_split: 0.9

# This parameters are passed to the model
model_args:
  lr: 0.001
  num_classes: 5
