experiment_name: "ptbdb_vanilla_rnn"

# Model and dataset for experiment
model: "vanilla_rnn"
dataset: "ptbdb"

seed: 1234

# Training parameters
device: "cpu"
batch_size: 32
n_epochs: 200
early_stopping: true
patience: 10
train_val_split: 0.9

# This parameters are passed to the model
model_args:
  hidden_size: 100
  num_layers: 1
  lr: 0.001
  num_classes: 1
  optimizer: "adam"
  criterion: "binary_cross_entropy"
